/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formazionecalciatori;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author 39333
 */
public class FormCalciatore extends javax.swing.JFrame {
    Squadra squadra;
    Calciatore calciatore;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCalciatore.class.getName());

    /**
     * Creates new form FormCalciatore
     */
    public FormCalciatore() {
        initComponents();
        calciatore = new Calciatore("ANGI");
        squadra = new Squadra(calciatore);
        aggiornaStatistiche();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/immagini/Yildiz.jpeg"));
        Image img = icon.getImage().getScaledInstance(190, 150, Image.SCALE_SMOOTH);
        lblImmagine.setIcon(new ImageIcon(img));
        
        btnRiabilita.setEnabled(false);
        lblNome.setText(calciatore.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        lblImmagine = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSvolgiAllenamento = new javax.swing.JButton();
        lblAllenamento1 = new javax.swing.JLabel();
        lblAllenatore1 = new javax.swing.JLabel();
        lblAllenamento2 = new javax.swing.JLabel();
        lblAllenatore2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        cmbAllenamento = new javax.swing.JComboBox<>();
        cmbAllenatore = new javax.swing.JComboBox<>();
        btnSelezionaAllenamento = new javax.swing.JButton();
        btnSelezionaAllenatore = new javax.swing.JButton();
        btnInfortunio = new javax.swing.JButton();
        btnLeggenda = new javax.swing.JButton();
        lblOverall = new javax.swing.JLabel();
        lblAbilità = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRiabilita = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        lblTitolo.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("FORMAZIONE GIOVANI TALENTI");

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSvolgiAllenamento.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnSvolgiAllenamento.setText("SVOLGI ALLENAMENTO");
        btnSvolgiAllenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSvolgiAllenamentoActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSvolgiAllenamento, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReset)
                        .addGap(0, 204, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAllenamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAllenatore1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(lblAllenamento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAllenatore2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReset)
                .addGap(20, 20, 20)
                .addComponent(lblAllenatore1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAllenamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAllenamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAllenatore2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSvolgiAllenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cmbAllenamento.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmbAllenamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "SPRINT [pac]", "CALCI PIAZZATI [sho]", "TRIANGOLAZIONI [pas]", " SLALOM [dri]", "UNO CONTRO UNO [def]", "CIRCUITI [phy]" }));

        cmbAllenatore.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        cmbAllenatore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "PREPARATORE ATLETICO [pac]", "PREPARATORE PIAZZATI [sho]", "PREPARATORE TECNICO [pas]", "PREPARATORE INDIVIDUALE [dri]", "PREPARATORE TATTICO [def]", "PREPARATORE FISICO [phy]" }));

        btnSelezionaAllenamento.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnSelezionaAllenamento.setText("Seleziona Allenamento");
        btnSelezionaAllenamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelezionaAllenamentoActionPerformed(evt);
            }
        });

        btnSelezionaAllenatore.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnSelezionaAllenatore.setText("Seleziona Allenatore");
        btnSelezionaAllenatore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelezionaAllenatoreActionPerformed(evt);
            }
        });

        btnInfortunio.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnInfortunio.setText("INFORTUNIO");
        btnInfortunio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfortunioActionPerformed(evt);
            }
        });

        btnLeggenda.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnLeggenda.setText("LEGGENDA");
        btnLeggenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeggendaActionPerformed(evt);
            }
        });

        lblOverall.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        lblOverall.setForeground(new java.awt.Color(255, 255, 255));
        lblOverall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAbilità.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblAbilità.setForeground(new java.awt.Color(255, 255, 255));
        lblAbilità.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OV");

        btnRiabilita.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        btnRiabilita.setText("RIABILITA");
        btnRiabilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiabilitaActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOverall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImmagine, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(lblAbilità, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLeggenda, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInfortunio))
                            .addComponent(cmbAllenamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSelezionaAllenatore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbAllenatore, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSelezionaAllenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRiabilita)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitolo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(cmbAllenamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelezionaAllenamento)
                                .addGap(44, 44, 44)
                                .addComponent(cmbAllenatore, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelezionaAllenatore)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(btnRiabilita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnInfortunio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLeggenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblOverall, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblImmagine, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAbilità, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSvolgiAllenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSvolgiAllenamentoActionPerformed
        if (squadra.getAllenatori().size() == 0 || squadra.getAllenamenti().size() == 0) {
            return;
        }
        for (int i = 0; i < squadra.getAllenatori().size(); i++) {
            Allenatore a = squadra.getAllenatori().get(i);
            for (int j = 0; j < squadra.getAllenamenti().size(); j++) {
                Allenamento al = squadra.getAllenamenti().get(j);
                squadra.eseguiAllenamento(al, a);
            }
        }
        lblOverall.setText(calciatore.getOverall());
        aggiornaStatistiche();
        btnSelezionaAllenamento.setEnabled(false);
        btnSelezionaAllenatore.setEnabled(false);
    }//GEN-LAST:event_btnSvolgiAllenamentoActionPerformed

    private void btnSelezionaAllenamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelezionaAllenamentoActionPerformed
        if (cmbAllenamento.getSelectedIndex() == 0) {
            return;
        }
        setAllenamento();
    }//GEN-LAST:event_btnSelezionaAllenamentoActionPerformed

    private void btnSelezionaAllenatoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelezionaAllenatoreActionPerformed
        if (cmbAllenatore.getSelectedIndex() == 0) {
            return;
        }
        setAllenatore();      
    }//GEN-LAST:event_btnSelezionaAllenatoreActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        squadra.getAllenatori().clear();
        squadra.getAllenamenti().clear();
        lblAllenatore1.setIcon(null);
        lblAllenatore2.setIcon(null);
        lblAllenamento1.setText("");
        lblAllenamento2.setText("");
        btnSelezionaAllenamento.setEnabled(true);
        btnSelezionaAllenatore.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLeggendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeggendaActionPerformed
        squadra.aiutoLeggenda();
        btnLeggenda.setEnabled(false);
        aggiornaStatistiche();
    }//GEN-LAST:event_btnLeggendaActionPerformed

    private void btnInfortunioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfortunioActionPerformed
        btnSvolgiAllenamento.setEnabled(false);
        btnLeggenda.setEnabled(false);
        btnRiabilita.setEnabled(true);
    }//GEN-LAST:event_btnInfortunioActionPerformed

    private void btnRiabilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiabilitaActionPerformed
        squadra.infortunio();
        btnSvolgiAllenamento.setEnabled(true);
        btnLeggenda.setEnabled(true);
        btnRiabilita.setEnabled(false);
    }//GEN-LAST:event_btnRiabilitaActionPerformed
    
    private void setAllenatore() {
        int i = cmbAllenatore.getSelectedIndex();
        if(i == 0) {
            return;
        }
        String all = cmbAllenatore.getSelectedItem().toString();
        Allenatore a;
        String path;

        switch(all) {
            case "PREPARATORE ATLETICO [pac]":
                a = new Allenatore(Abilità.PAC, "ZIDANE");
                path = "/immagini/Zidane.png";
                break;
            case "PREPARATORE PIAZZATI [sho]":
                a = new Allenatore(Abilità.SHO, "ALLEGRI");
                path = "/immagini/Allegri.png";
                break;
            case "PREPARATORE TECNICO [pas]":
                a = new Allenatore(Abilità.PAS, "ANCELOTTI");
                path = "/immagini/Ancelotti.png";
                break;
            case "PREPARATORE INDIVIDUALE [dri]":
                a = new Allenatore(Abilità.DRI, "GUARDIOLA");
                path = "/immagini/Guardiola.png";
                break;
            case "PREPARATORE TATTICO [def]":
                a = new Allenatore(Abilità.DEF, "SPALLETTI");
                path = "/immagini/Spalletti.png";
                break;
            case "PREPARATORE FISICO [phy]":
                a = new Allenatore(Abilità.PHY, "CONTE");
                path = "/immagini/Conte.png";
                break;
            default:
                return;
        }
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH);
        a.setIcon(new ImageIcon(img));
        if(squadra.addAllenatore(a)) {
            aggiornaLabelAllenatori();
            cmbAllenatore.setSelectedIndex(0);
        }
    }
    
    private void setAllenamento() {
        int i = cmbAllenamento.getSelectedIndex();
        if(i == 0) {
            return;
        }
        String all = cmbAllenamento.getSelectedItem().toString();
        Allenamento al = null;

        switch(all) {
            case "SPRINT [pac]":
                al = new Sprint(10);
                break;
            case "CALCI PIAZZATI [sho]":
                al = new CalcioPiazzato(20, true);
                break;
            case "TRIANGOLAZIONI [pas]":
                al = new Triangolazione();
                break;
            case "SLALOM [dri]":
                al = new Slalom();
                break;
            case "UNO CONTRO UNO [def]":
                al = new UnoControUno(77);
                break;
            case "CIRCUITI [phy]":
                al = new Circuito(30, 3);
                break;
            default:
                return;
        }
        if(squadra.addAllenamento(al)) {
            aggiornaLabelAllenamenti();
            cmbAllenamento.setSelectedIndex(0);
        }
    }
    
    private void aggiornaLabelAllenatori() {
        if (squadra.getAllenatori().size() > 0) {
            lblAllenatore1.setIcon(squadra.getAllenatori().get(0).getIcon());
        }
        else {
            lblAllenatore1.setIcon(null);
        }
        if (squadra.getAllenatori().size() > 1) {
            lblAllenatore2.setIcon(squadra.getAllenatori().get(1).getIcon());
        }
        else {
            lblAllenatore2.setIcon(null);
        }
    }
    
    private void aggiornaLabelAllenamenti() {
        if (squadra.getAllenamenti().size() > 0){
            lblAllenamento1.setText(squadra.getAllenamenti().get(0).toString());
        }
        else {
            lblAllenamento1.setText("");
        }
        if (squadra.getAllenamenti().size() > 1) {
            lblAllenamento2.setText(squadra.getAllenamenti().get(1).toString());
        }
        else {
            lblAllenamento2.setText("");
        }
    }
    
    private void aggiornaStatistiche() {
        lblAbilità.setText(calciatore.getAbilità());
        lblOverall.setText(calciatore.getOverall());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCalciatore().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfortunio;
    private javax.swing.JButton btnLeggenda;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRiabilita;
    private javax.swing.JButton btnSelezionaAllenamento;
    private javax.swing.JButton btnSelezionaAllenatore;
    private javax.swing.JButton btnSvolgiAllenamento;
    private javax.swing.JComboBox<String> cmbAllenamento;
    private javax.swing.JComboBox<String> cmbAllenatore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAbilità;
    private javax.swing.JLabel lblAllenamento1;
    private javax.swing.JLabel lblAllenamento2;
    private javax.swing.JLabel lblAllenatore1;
    private javax.swing.JLabel lblAllenatore2;
    private javax.swing.JLabel lblImmagine;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOverall;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
